const Discord = require('discord.js')
const config = require('./config.json')
const client = new Discord.Client()
const { Shoukaku } = require('shoukaku')
const lavalinkserver = require('./lavalink-server.json')
client.commands = new Discord.Collection()
client.aliases = new Discord.Collection()
require('./core/events.js')(client)
require('./core/functions.js')(client)
client.login(config.token)
Shoukaku.build(lavalinkserver)
